"""initial postgres schema v0.1

Revision ID: 09b71ab45512
Revises: 
Create Date: 2026-09-04 01:44:41.594416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09b71ab45512'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dragons',
    sa.Column('dragon_id', sa.Text(), nullable=False),
    sa.Column('archetype_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('age_stage', sa.Text(), nullable=False),
    sa.Column('appearance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('temperament_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_location', sa.Text(), nullable=False),
    sa.Column('health_state', sa.Text(), nullable=False),
    sa.Column('energy', sa.Numeric(), nullable=False),
    sa.Column('hunger', sa.Numeric(), nullable=False),
    sa.Column('alertness', sa.Numeric(), nullable=False),
    sa.Column('behavior_state', sa.Text(), nullable=False),
    sa.Column('taming_state', sa.Text(), nullable=False),
    sa.CheckConstraint("age_stage IN ('hatchling', 'juvenile', 'young_adult', 'adult')", name='ck_dragons_age_stage'),
    sa.CheckConstraint("behavior_state IN ('resting', 'feeding', 'wandering', 'watching', 'avoiding', 'threatening', 'attacking', 'following', 'flying')", name='ck_dragons_behavior_state'),
    sa.CheckConstraint("jsonb_typeof(temperament_traits) = 'array'", name='ck_dragons_temperament_traits_json_array'),
    sa.CheckConstraint("taming_state IN ('wild', 'tolerant', 'bonding', 'tamed')", name='ck_dragons_taming_state'),
    sa.PrimaryKeyConstraint('dragon_id')
    )
    op.create_table('npcs',
    sa.Column('npc_id', sa.Text(), nullable=False),
    sa.Column('current_location', sa.Text(), nullable=False),
    sa.Column('current_activity', sa.Text(), nullable=True),
    sa.Column('current_goal', sa.Text(), nullable=True),
    sa.Column('mood', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('npc_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('species', sa.Text(), nullable=True),
    sa.Column('occupation', sa.Text(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("jsonb_typeof(traits) = 'array'", name='ck_players_traits_json_array'),
    sa.CheckConstraint("species IN ('human', 'dragon')", name='ck_players_species'),
    sa.CheckConstraint('jsonb_array_length(traits) <= 5', name='ck_players_traits_max_items'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('world_state_entries',
    sa.Column('state_id', sa.Text(), nullable=False),
    sa.Column('state_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_event_type', sa.Text(), nullable=True),
    sa.Column('source_event_id', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('(source_event_type IS NULL AND source_event_id IS NULL) OR (source_event_type IS NOT NULL AND source_event_id IS NOT NULL)', name='ck_world_state_entries_source_fields_together'),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('dragon_eggs',
    sa.Column('egg_id', sa.Text(), nullable=False),
    sa.Column('archetype_id', sa.Text(), nullable=True),
    sa.Column('acquired_by_player_id', sa.Text(), nullable=False),
    sa.Column('incubation_state', sa.Text(), nullable=False),
    sa.Column('incubation_progress', sa.Numeric(), nullable=False),
    sa.Column('acquired_event_type', sa.Text(), nullable=False),
    sa.Column('acquired_event_id', sa.Text(), nullable=False),
    sa.Column('hatched_dragon_id', sa.Text(), nullable=True),
    sa.Column('hatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("hatched_dragon_id IS NULL OR incubation_state = 'hatched'", name='ck_dragon_eggs_hatched_state'),
    sa.CheckConstraint('(hatched_dragon_id IS NULL AND hatched_at IS NULL) OR (hatched_dragon_id IS NOT NULL AND hatched_at IS NOT NULL)', name='ck_dragon_eggs_hatching_fields_together'),
    sa.ForeignKeyConstraint(['acquired_by_player_id'], ['players.player_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hatched_dragon_id'], ['dragons.dragon_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('egg_id'),
    sa.UniqueConstraint('hatched_dragon_id')
    )
    op.create_table('interaction_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('npc_id', sa.Text(), nullable=True),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('world_hour', sa.SmallInteger(), nullable=False),
    sa.Column('location_id', sa.Text(), nullable=False),
    sa.Column('player_utterance', sa.Text(), nullable=False),
    sa.Column('npc_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('player_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('memory_candidate', sa.Boolean(), nullable=True),
    sa.Column('relationship_signal', sa.Text(), nullable=True),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("btrim(player_utterance) <> ''", name='ck_interaction_events_utterance_nonempty'),
    sa.CheckConstraint("event_type <> 'npc_dialogue' OR (npc_id IS NOT NULL AND npc_response IS NOT NULL AND topic IS NOT NULL AND memory_candidate IS NOT NULL AND relationship_signal IS NOT NULL)", name='ck_interaction_events_npc_dialogue_fields'),
    sa.CheckConstraint("jsonb_typeof(player_claims) = 'array'", name='ck_interaction_events_player_claims_json_array'),
    sa.CheckConstraint("relationship_signal IS NULL OR relationship_signal IN ('none', 'potential_positive', 'potential_negative')", name='ck_interaction_events_relationship_signal'),
    sa.CheckConstraint('topic IS NULL OR char_length(topic) BETWEEN 1 AND 80', name='ck_interaction_events_topic_length'),
    sa.CheckConstraint('world_day >= 1', name='ck_interaction_events_world_day'),
    sa.CheckConstraint('world_hour BETWEEN 0 AND 23', name='ck_interaction_events_world_hour'),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.npc_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('npc_relationships',
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('npc_id', sa.Text(), nullable=False),
    sa.Column('familiarity', sa.SmallInteger(), nullable=False),
    sa.Column('trust', sa.SmallInteger(), nullable=False),
    sa.Column('attitude', sa.Text(), nullable=False),
    sa.Column('applied_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_source_event_id', sa.Text(), nullable=False),
    sa.CheckConstraint("attitude IN ('hostile', 'wary', 'neutral', 'warm')", name='ck_npc_relationships_attitude'),
    sa.CheckConstraint("jsonb_typeof(applied_event_ids) = 'array' AND jsonb_array_length(applied_event_ids) > 0", name='ck_npc_relationships_applied_events'),
    sa.CheckConstraint('familiarity BETWEEN 0 AND 3', name='ck_npc_relationships_familiarity'),
    sa.CheckConstraint('trust BETWEEN -2 AND 2', name='ck_npc_relationships_trust'),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.npc_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('player_id', 'npc_id')
    )
    op.create_table('player_states',
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('current_location', sa.Text(), nullable=False),
    sa.Column('inventory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("jsonb_typeof(goals) = 'array'", name='ck_player_states_goals_json_array'),
    sa.CheckConstraint("jsonb_typeof(inventory) = 'array'", name='ck_player_states_inventory_json_array'),
    sa.CheckConstraint('jsonb_array_length(goals) <= 5', name='ck_player_states_goals_max_items'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('dragon_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('dragon_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=True),
    sa.Column('source_interaction_event_id', sa.Text(), nullable=True),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('world_hour', sa.SmallInteger(), nullable=False),
    sa.Column('location_id', sa.Text(), nullable=False),
    sa.Column('milestone_key', sa.Text(), nullable=True),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("event_type IN ('dragon_first_encounter', 'dragon_accepts_food', 'dragon_allows_close_presence', 'dragon_allows_touch', 'player_heals_dragon', 'player_rescues_dragon', 'dragon_rescues_player', 'shared_danger_survived', 'dragon_tamed', 'dragon_accepts_mount', 'first_shared_flight')", name='ck_dragon_events_event_type'),
    sa.CheckConstraint('world_day >= 1', name='ck_dragon_events_world_day'),
    sa.CheckConstraint('world_hour BETWEEN 0 AND 23', name='ck_dragon_events_world_hour'),
    sa.ForeignKeyConstraint(['dragon_id'], ['dragons.dragon_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_interaction_event_id'], ['interaction_events.event_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('dragon_id', 'source_interaction_event_id', 'event_type', name='uq_dragon_events_grounded_source')
    )
    op.create_table('npc_memories',
    sa.Column('memory_id', sa.Text(), nullable=False),
    sa.Column('npc_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('source_event_id', sa.Text(), nullable=True),
    sa.Column('memory_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('epistemic_status', sa.Text(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('world_hour', sa.SmallInteger(), nullable=False),
    sa.Column('location_id', sa.Text(), nullable=False),
    sa.Column('created_from_topic', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("btrim(content) <> ''", name='ck_npc_memories_content_nonempty'),
    sa.CheckConstraint("epistemic_status IN ('reported_by_player', 'observed_interaction')", name='ck_npc_memories_epistemic_status'),
    sa.CheckConstraint("memory_type IN ('player_intention', 'player_claim', 'interaction')", name='ck_npc_memories_memory_type'),
    sa.CheckConstraint('char_length(created_from_topic) BETWEEN 1 AND 80', name='ck_npc_memories_topic_length'),
    sa.CheckConstraint('world_day >= 1', name='ck_npc_memories_world_day'),
    sa.CheckConstraint('world_hour BETWEEN 0 AND 23', name='ck_npc_memories_world_hour'),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.npc_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_event_id'], ['interaction_events.event_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('memory_id'),
    sa.UniqueConstraint('npc_id', 'source_event_id', name='uq_npc_memories_npc_source_event')
    )
    op.create_table('player_dragon_bonds',
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('dragon_id', sa.Text(), nullable=False),
    sa.Column('familiarity', sa.SmallInteger(), nullable=False),
    sa.Column('trust', sa.SmallInteger(), nullable=False),
    sa.Column('fear', sa.SmallInteger(), nullable=False),
    sa.Column('bond', sa.SmallInteger(), nullable=False),
    sa.Column('riding_unlocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_significant_event_id', sa.Text(), nullable=True),
    sa.CheckConstraint('bond BETWEEN 0 AND 5', name='ck_player_dragon_bonds_bond'),
    sa.CheckConstraint('familiarity BETWEEN 0 AND 5', name='ck_player_dragon_bonds_familiarity'),
    sa.CheckConstraint('fear BETWEEN 0 AND 5', name='ck_player_dragon_bonds_fear'),
    sa.CheckConstraint('trust BETWEEN -3 AND 5', name='ck_player_dragon_bonds_trust'),
    sa.ForeignKeyConstraint(['dragon_id'], ['dragons.dragon_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['last_significant_event_id'], ['dragon_events.event_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('player_id', 'dragon_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_dragon_bonds')
    op.drop_table('npc_memories')
    op.drop_table('dragon_events')
    op.drop_table('player_states')
    op.drop_table('npc_relationships')
    op.drop_table('interaction_events')
    op.drop_table('dragon_eggs')
    op.drop_table('world_state_entries')
    op.drop_table('players')
    op.drop_table('npcs')
    op.drop_table('dragons')
    # ### end Alembic commands ###
